sudo: required

language: java

services:
  - docker

before_script:
#  - cd src/ui && npm install
  - docker run -d -p 0.0.0.0:27017:27017 mongo
  - docker ps -a

script:
  - ./gradlew npmInstall buildDist stageUI build

# as stated in https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_script:
  - ls -lah .